import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export type OrderStatus = 'placed' | 'confirmed' | 'packed' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled';

export interface Order {
  id: string;
  order_number: string;
  status: OrderStatus;
  total_amount: number;
  shipping_address: {
    fullName: string;
    phone: string;
    email: string;
    address: string;
    city: string;
    state: string;
    pincode: string;
  };
  items: Array<{
    id: string;
    name: string;
    quantity: number;
    price: number;
    image?: string;
  }>;
  placed_at: string;
  confirmed_at: string | null;
  packed_at: string | null;
  shipped_at: string | null;
  out_for_delivery_at: string | null;
  delivered_at: string | null;
  estimated_delivery: string | null;
  tracking_number: string | null;
  updated_at: string;
}

export const useOrders = () => {
  const { user } = useAuth();
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(false);

  const fetchOrders = async () => {
    if (!user) return;

    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });

      if (error) throw error;

      // Cast the data to match our Order interface
      const typedOrders: Order[] = (data || []).map(order => ({
        ...order,
        status: order.status as OrderStatus,
        shipping_address: order.shipping_address as Order['shipping_address'],
        items: order.items as Order['items'],
      }));

      setOrders(typedOrders);
    } catch (error) {
      console.error('Error fetching orders:', error);
    } finally {
      setLoading(false);
    }
  };

  const createOrder = async (orderData: {
    total_amount: number;
    shipping_address: Order['shipping_address'];
    items: Order['items'];
    estimated_delivery?: string;
  }) => {
    if (!user) {
      toast.error('Please login to place an order');
      return null;
    }

    try {
      const { data, error } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          total_amount: orderData.total_amount,
          shipping_address: orderData.shipping_address,
          items: orderData.items,
          estimated_delivery: orderData.estimated_delivery,
          order_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      const typedOrder: Order = {
        ...data,
        status: data.status as OrderStatus,
        shipping_address: data.shipping_address as Order['shipping_address'],
        items: data.items as Order['items'],
      };

      setOrders(prev => [typedOrder, ...prev]);
      return typedOrder;
    } catch (error) {
      console.error('Error creating order:', error);
      toast.error('Failed to create order');
      return null;
    }
  };

  // Set up realtime subscription for order updates
  useEffect(() => {
    if (!user) return;

    fetchOrders();

    const channel = supabase
      .channel('orders-changes')
      .on(
        'postgres_changes',
        {
          event: 'UPDATE',
          schema: 'public',
          table: 'orders',
          filter: `user_id=eq.${user.id}`,
        },
        (payload) => {
          const updatedOrder = payload.new as Order;
          setOrders(prev =>
            prev.map(order =>
              order.id === updatedOrder.id
                ? {
                  ...updatedOrder,
                  status: updatedOrder.status as OrderStatus,
                  shipping_address: updatedOrder.shipping_address as Order['shipping_address'],
                  items: updatedOrder.items as Order['items'],
                }
                : order
            )
          );
          toast.info(`Order ${updatedOrder.order_number} status updated to ${updatedOrder.status.replace('_', ' ')}`);
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user]);

  const cancelOrder = async (orderId: string) => {
    if (!user) {
      toast.error('Please login to cancel an order');
      return false;
    }

    try {
      const { error } = await supabase
        .from('orders')
        .update({
          status: 'cancelled',
          updated_at: new Date().toISOString()
        })
        .eq('id', orderId)
        .eq('user_id', user.id);

      if (error) throw error;

      // Manually update local state for immediate UI feedback
      setOrders(prev => prev.map(o =>
        o.id === orderId
          ? { ...o, status: 'cancelled' as OrderStatus, updated_at: new Date().toISOString() }
          : o
      ));

      toast.success('Order cancelled successfully');
      return true;
    } catch (error) {
      console.error('Error cancelling order:', error);
      toast.error('Failed to cancel order');
      return false;
    }
  };

  return { orders, loading, fetchOrders, createOrder, cancelOrder };
};
